In [1]:
# 1. Load the cleaned dataset
import pandas as pd
from sklearn.preprocessing import LabelEncoder

df = pd.read_csv("../data/processed/clean_flights.csv")

In [2]:
df["ScheduledDeparture"] = pd.to_datetime(df["ScheduledDeparture"])

df["DepartureHour"] = df["ScheduledDeparture"].dt.hour
df["Month"] = df["ScheduledDeparture"].dt.month
df["DayOfWeek"] = df["ScheduledDeparture"].dt.dayofweek

df["Delayed"] = (df["DelayMinutes"] >= 15).astype(int)

In [3]:
df.head()

,FlightID,Airline,FlightNumber,Origin,Destination,ScheduledDeparture,ActualDeparture,ScheduledArrival,ActualArrival,DelayMinutes,DelayReason,Cancelled,Diverted,AircraftType,TailNumber,Distance,DepartureHour,Month,DayOfWeek,Delayed
0,1,United,4558,ORD,MIA,2024-09-01 08:11:00,2024-09-01 08:30,2024-09-01 12:11,2024-09-01 12:19,8,Weather,True,False,Boeing 737,N71066,1031,8,9,6,0
1,2,Delta,8021,LAX,MIA,2024-09-01 10:25:00,2024-09-01 10:41,2024-09-01 13:25,2024-09-01 13:27,2,Air Traffic Control,True,True,Airbus A320,N22657,1006,10,9,6,0
2,3,Southwest,7520,DFW,SFO,2024-09-01 16:53:00,2024-09-01 17:05,2024-09-01 17:53,2024-09-01 18:07,14,Weather,True,True,Boeing 737,N95611,2980,16,9,6,0
3,4,Delta,2046,ORD,BOS,2024-09-01 14:44:00,2024-09-01 15:04,2024-09-01 18:44,2024-09-01 18:34,-10,NaN,False,False,Boeing 777,N90029,1408,14,9,6,0
4,5,Delta,6049,LAX,SEA,2024-09-01 01:51:00,2024-09-01 02:08,2024-09-01 05:51,2024-09-01 06:15,24,Air Traffic Control,False,True,Boeing 737,N27417,2298,1,9,6,1

In [4]:
selected_columns = [
    "Airline",
    "Origin",
    "Destination",
    "DepartureHour",
    "Month",
    "DayOfWeek",
    "Distance",
    "AircraftType",
    "Delayed"
]

df = df[selected_columns]

In [5]:
df.head()

,Airline,Origin,Destination,DepartureHour,Month,DayOfWeek,Distance,AircraftType,Delayed
0,United,ORD,MIA,8,9,6,1031,Boeing 737,0
1,Delta,LAX,MIA,10,9,6,1006,Airbus A320,0
2,Southwest,DFW,SFO,16,9,6,2980,Boeing 737,0
3,Delta,ORD,BOS,14,9,6,1408,Boeing 777,0
4,Delta,LAX,SEA,1,9,6,2298,Boeing 737,1

In [6]:
df.dtypes

Airline          object
Origin           object
Destination      object
DepartureHour     int32
Month             int32
DayOfWeek         int32
Distance          int64
AircraftType     object
Delayed           int64
dtype: object

In [7]:
df.isnull().sum()

Airline          0
Origin           0
Destination      0
DepartureHour    0
Month            0
DayOfWeek        0
Distance         0
AircraftType     0
Delayed          0
dtype: int64

In [8]:
airline_encoder = LabelEncoder()
origin_encoder = LabelEncoder()
destination_encoder = LabelEncoder()
aircraft_encoder = LabelEncoder()

In [9]:
df["Airline"] = airline_encoder.fit_transform(df["Airline"])

df["Origin"] = origin_encoder.fit_transform(df["Origin"])

df["Destination"] = destination_encoder.fit_transform(df["Destination"])

df["AircraftType"] = aircraft_encoder.fit_transform(df["AircraftType"])

In [10]:
df.head()

,Airline,Origin,Destination,DepartureHour,Month,DayOfWeek,Distance,AircraftType,Delayed
0,3,4,2,8,9,6,1031,1,0
1,1,3,2,10,9,6,1006,0,0
2,2,1,4,16,9,6,2980,1,0
3,1,4,0,14,9,6,1408,2,0
4,1,3,3,1,9,6,2298,1,1

In [11]:
print(df.columns)

Index(['Airline', 'Origin', 'Destination', 'DepartureHour', 'Month',
       'DayOfWeek', 'Distance', 'AircraftType', 'Delayed'],
      dtype='object')

In [12]:
X = df.drop("Delayed", axis=1)

y = df["Delayed"]

In [13]:
print(X.head())

   Airline  Origin  Destination  DepartureHour  Month  DayOfWeek  Distance  \
0        3       4            2              8      9          6      1031
1        1       3            2             10      9          6      1006
2        2       1            4             16      9          6      2980
3        1       4            0             14      9          6      1408
4        1       3            3              1      9          6      2298

   AircraftType
0             1
1             0
2             1
3             2
4             1

In [14]:
print(y.head())

0    0
1    0
2    0
3    0
4    1
Name: Delayed, dtype: int64

In [15]:
print(df["Delayed"].value_counts())

Delayed
0    1065676
1     681951
Name: count, dtype: int64

In [16]:
print(df["Delayed"].value_counts(normalize=True))

Delayed
0    0.609785
1    0.390215
Name: proportion, dtype: float64